import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";
import { MoviesContextProvider } from "./store/context";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "PcariMovie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={dmSans.className}>
          <Navbar />
          {children}
          <Footer />
        </body>
    </html>
  );
}
